CREATE TABLE Accounts (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    
    FOREIGN KEY (UserId) REFERENCES Users(Id),
);

CREATE INDEX IX_Accounts_UserId ON Accounts(UserId);